# Generated by Django 5.2.3 on 2025-08-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_date", models.DateField(null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, null=True, verbose_name="название проекта"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
