# Generated by Django 5.2.3 on 2025-07-08 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Dashbords", "0001_initial"),
        ("Projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор проекта",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="dashbord",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Dashbords.dashbord",
                verbose_name="Канбан доска",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="члены проекта",
            ),
        ),
    ]
