# Generated by Django 5.2.3 on 2025-07-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Dashbords",
            "0002_dashbord_name_dashbord_project_dashbord_update_date_and_more",
        ),
        ("Projects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="update_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="dashbord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_dashbords",
                to="Dashbords.dashbord",
                verbose_name="Канбан доска",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="члены проекта",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                blank=True, null=True, verbose_name="название проекта"
            ),
        ),
    ]
