# Generated by Django 5.2.3 on 2025-07-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Dashbords",
            "0002_dashbord_name_dashbord_project_dashbord_update_date_and_more",
        ),
        ("Projects", "0003_project_update_date_alter_project_dashbord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="dashbord",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_dashbords",
                to="Dashbords.dashbord",
                verbose_name="Канбан доска",
            ),
        ),
    ]
