# Generated by Django 5.2.3 on 2025-07-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="название задачи")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Высокий"), (2, "Средний"), (3, "Низкий")],
                        null=True,
                        verbose_name="приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="дедлайн"),
                ),
                ("hours", models.DurationField(verbose_name="время выполнения")),
            ],
        ),
    ]
