# Generated by Django 5.2.3 on 2025-08-08 08:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_date", models.DateField(null=True)),
                (
                    "name",
                    models.CharField(
                        default="Без названия", verbose_name="название задачи"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Высокий"), (2, "Средний"), (3, "Низкий")],
                        null=True,
                        verbose_name="приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="дедлайн"),
                ),
                (
                    "hours",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="время выполнения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To Do"),
                            ("in_progress", "In progress"),
                            ("done", "done"),
                        ],
                        default="to_do",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
