# Generated by Django 5.2.3 on 2025-08-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="story_points",
            field=models.PositiveIntegerField(default=0, verbose_name="Очки"),
        ),
    ]
