# Generated by Django 5.2.3 on 2025-07-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="Tasks.task",
            ),
        ),
    ]
