# Generated by Django 5.2.3 on 2025-08-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks", "0003_task_story_points"),
        ("analytics", "0002_alter_userperformance_tasks_overdue_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_sprint",
                to="analytics.sprint",
                verbose_name="спринт",
            ),
        ),
    ]
