# Generated by Django 5.2.3 on 2025-07-18 13:17

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks", "0003_task_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task",
            new_name="parent",
        ),
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="update_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_execor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="оSтвественный",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="hours",
            field=models.DurationField(
                default=datetime.timedelta(0), verbose_name="время выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                default="Без названия", verbose_name="название задачи"
            ),
        ),
    ]
