# Generated by Django 5.2.3 on 2025-09-03 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashbords", "0002_initial"),
        ("Projects", "0002_initial"),
        ("Tasks", "0004_task_sprint"),
        ("analytics", "0003_sprint_update_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Высокий"), (2, "Средний"), (3, "Низкий")],
                db_index=True,
                null=True,
                verbose_name="приоритет",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["executor", "status", "deadline"],
                name="idx_executor_status_deadline",
            ),
        ),
    ]
