# Generated by Django 5.2.3 on 2025-07-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashbords", "0004_alter_column_dashbord"),
        ("Tasks", "0004_rename_task_task_parent_task_author_task_update_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="column",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_column",
                to="Dashbords.column",
            ),
        ),
    ]
