# Generated by Django 5.2.3 on 2025-08-04 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0004_alter_project_dashbord"),
        ("Tasks", "0005_task_column"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_project",
                to="Projects.project",
                verbose_name="id проекта",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_execor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="отвественный",
            ),
        ),
    ]
