# Generated by Django 5.2.3 on 2025-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashbords", "0001_initial"),
        ("Projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashbord",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dashbord",
            name="project",
            field=models.ManyToManyField(related_name="dashbords", to="Projects.project"),
        ),
        migrations.AddField(
            model_name="dashbord",
            name="update_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="dashbord",
            name="column",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="колонка"
            ),
        ),
    ]
