# Generated by Django 5.2.3 on 2025-08-08 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Dashbords", "0001_initial"),
        ("Projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashbord",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashbords",
                to="Projects.project",
                verbose_name="проект",
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="dashbord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="Dashbords.dashbord",
            ),
        ),
    ]
