# Generated by Django 5.2.3 on 2025-07-28 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Dashbords",
            "0002_dashbord_name_dashbord_project_dashbord_update_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashbord",
            name="column",
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_date", models.DateField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "dashbord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashbords.dashbord",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
