# Generated by Django 5.2.3 on 2025-07-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashbords", "0003_remove_dashbord_column_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="dashbord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="Dashbords.dashbord",
            ),
        ),
    ]
