# Generated by Django 5.2.3 on 2025-07-08 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания метрики"
                    ),
                ),
                (
                    "total_task",
                    models.PositiveIntegerField(default=0, verbose_name="Всего задач"),
                ),
                (
                    "overdue_task",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Просрочные задачи"
                    ),
                ),
                (
                    "completed_task",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Выполненные задачи"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Projects.project",
                        verbose_name="проект",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="название отчета")),
                (
                    "format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("CSV", "CSV"), ("XLSX", "Excel")],
                        default="CSV",
                        verbose_name="формат отчета",
                    ),
                ),
                ("file", models.FileField(upload_to="reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                        ],
                        max_length=10,
                        verbose_name="Периодичность",
                    ),
                ),
                ("next_send", models.DateTimeField(verbose_name="Следующая отправка")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "recipients",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Получатели"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.report",
                        verbose_name="Отчет",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_projects",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кол-во проектов"
                    ),
                ),
                (
                    "total_task",
                    models.PositiveIntegerField(default=0, verbose_name="Кол-во задач"),
                ),
                (
                    "completed_tasks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кол-во выполненных задач"
                    ),
                ),
                ("tasks_overdue", models.PositiveIntegerField(default=0)),
                ("tasks_assigned", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участник проекта",
                    ),
                ),
            ],
        ),
    ]
