# Generated by Django 5.2.3 on 2025-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduledreport",
            old_name="report",
            new_name="report_id",
        ),
        migrations.AddField(
            model_name="projectmetrics",
            name="update_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="update_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="scheduledreport",
            name="update_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="userperformance",
            name="update_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="name",
            field=models.CharField(blank=True, verbose_name="название отчета"),
        ),
    ]
