# Generated by Django 5.2.3 on 2025-08-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0002_initial"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userperformance",
            name="tasks_overdue",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кол-во просроченных задач"
            ),
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название спринта"),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "planned_points",
                    models.PositiveIntegerField(default=0, verbose_name="Очки на старте"),
                ),
                (
                    "completed_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Завершенные очки"
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprint_project",
                        to="Projects.project",
                        verbose_name="проект",
                    ),
                ),
            ],
        ),
    ]
