# Generated by Django 5.2.3 on 2025-08-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_userperformance_tasks_overdue_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="update_date",
            field=models.DateField(null=True),
        ),
    ]
