# Generated by Django 5.2.3 on 2025-09-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number",
            field=models.CharField(
                db_index=True, max_length=12, unique=True, verbose_name="номер телефона"
            ),
        ),
    ]
