# Generated by Django 5.2.3 on 2025-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="update_date",
            field=models.DateField(null=True),
        ),
    ]
