# Generated by Django 5.2.3 on 2025-07-18 13:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="update_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="reminder_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="дата напоминания"
            ),
        ),
    ]
