# Generated by Django 5.2.3 on 2025-07-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="read",
            new_name="is_read",
        ),
    ]
